name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
jobs:
  ethereum:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: cd ethereum && make build && make test
